"""Export a SessionContext as a Jupyter notebook and open it in VS Code.

The "Continue in Notebook..." bridge: reproduces the exact pipeline run in
the GUI so far, so the user can keep going with full notebook flexibility
(re-run with different parameters, compare runs side by side, etc.) -- see
the molass-gui design philosophy note in repo memory (2026-08-20).
"""
import os
import shutil
import subprocess
from tkinter import filedialog, messagebox

import nbformat as nbf


def _md(source):
    return nbf.v4.new_markdown_cell(source)


def _code(source):
    return nbf.v4.new_code_cell(source)


def _upgrade_call(model_info):
    model_key = model_info['model']
    pore_dist = model_info.get('pore_dist')
    ln_pore_sigma = model_info.get('ln_pore_sigma')
    kwargs = ""
    if pore_dist is not None:
        kwargs += f", pore_dist={pore_dist!r}"
    if ln_pore_sigma is not None:
        kwargs += f", model_params={{'ln_pore_sigma': {ln_pore_sigma!r}}}"
    return f"decomp = decomp.upgrade({model_key!r}{kwargs})"


def build_notebook(ctx):
    """Build an nbformat notebook reproducing ctx's pipeline so far."""
    cells = [_md(
        "# Molass session -- continued from GUI\n\n"
        "Generated by molass-gui's \"Continue in Notebook...\" so you can keep "
        "going with full notebook flexibility (re-run with different "
        "parameters, compare runs side by side, etc.)."
    )]

    cells.append(_code(
        "from molass.DataObjects import SecSaxsData as SSD\n\n"
        f"ssd = SSD(r\"{ctx.folder}\")\n"
        "trimmed = ssd.trimmed_copy()\n"
        "trimmed.plot_compact(baseline=True)"
    ))

    if ctx.num_components is not None:
        cells.append(_code(
            "corrected = trimmed.corrected_copy()\n"
            f"decomp = corrected.quick_decomposition(num_components={ctx.num_components})\n"
            "rgcurve = decomp.get_rg_curve()\n"
            "decomp.plot_components(rgcurve=rgcurve)"
        ))

    if ctx.model_info is not None and ctx.model_info['model'] != 'egh':
        cells.append(_code(_upgrade_call(ctx.model_info) + "\ndecomp.plot_components(rgcurve=rgcurve)"))

    if ctx.method is not None:
        cells.append(_code(
            "score = decomp.score(trimmed_ssd=trimmed)\n"
            "score.print_summary()\n"
            "score.plot()"
        ))
        # in_process, async_, monitor, and pipeline_recipe are all deliberately
        # omitted -- they already match the library's own defaults (False, True,
        # True, None), and this is the usual pattern anyway. Both the GUI and the
        # exported notebook now get the same subprocess+auto-recipe behavior "for
        # free" from the library default -- see
        # molass-library/Copilot/refactor/DESIGN_default_in_process_reversal.md.
        # method is always shown, even for 'BH': it incurs zero learning cost
        # (the user already saw/chose BH in the GUI's own combobox), so restating
        # it just makes an already-known fact explicit and reproducible. This
        # differs from in_process/async_/monitor above, which were never GUI-facing
        # choices -- surfacing them would require learning a new concept for no
        # benefit, which is what the "minimal learning cost" rule guards against.
        lines = [
            "# Sibling folder, not the GUI's own analysis_folder -- reusing that path",
            "# exactly can collide with the GUI's own run still using it (optimize_rigorously",
            "# would just reconnect to it instead of starting a fresh monitored run).",
            f'analysis_folder = r"{ctx.analysis_folder}_notebook"',
            "run_info = decomp.optimize_rigorously(",
            "    trimmed_ssd=trimmed,",
            f"    method={ctx.method.upper()!r},",
            "    analysis_folder=analysis_folder,",
            ")",
        ]
        cells.append(_code("\n".join(lines)))
        cells.append(_code("run_info.live_status()"))

    nb = nbf.v4.new_notebook()
    nb['cells'] = cells
    return nb


def _open_in_vscode(path):
    for exe in ("code-insiders", "code"):
        found = shutil.which(exe)
        if found:
            subprocess.Popen([found, path])
            return True
    return False


def export_and_open(ctx, parent_win):
    """Ask for a save path, write the notebook, open it in VS Code.

    Failures are shown as a messagebox rather than raised -- this is a
    convenience bridge, not a critical path; the GUI session keeps working
    regardless of the outcome.
    """
    from datetime import datetime
    # Timestamped default name -- a reused fixed name (e.g. molass_session.ipynb)
    # would silently reopen an already-open stale tab: VS Code's notebook editor
    # does not reliably auto-reload an open .ipynb when it changes on disk
    # externally, so re-exporting to the same path can appear to "not work"
    # even though the file itself was written correctly (see repo memory).
    default_name = f"molass_session_{datetime.now():%Y%m%d_%H%M%S}.ipynb"
    path = filedialog.asksaveasfilename(
        title="Save notebook as",
        defaultextension=".ipynb",
        filetypes=[("Jupyter Notebook", "*.ipynb")],
        initialfile=default_name,
        parent=parent_win,
    )
    if not path:
        return

    overwriting_existing = os.path.exists(path)

    try:
        nb = build_notebook(ctx)
        nbf.write(nb, path)
    except Exception as exc:
        messagebox.showerror("Export failed", str(exc), parent=parent_win)
        return

    if not _open_in_vscode(path):
        messagebox.showinfo(
            "Notebook saved",
            f"Saved to:\n{path}\n\n(VS Code CLI not found on PATH -- open it manually.)",
            parent=parent_win,
        )
    elif overwriting_existing:
        messagebox.showinfo(
            "Notebook updated",
            "If this notebook was already open in VS Code, its tab may not "
            "auto-refresh -- close and reopen the tab to see the update.",
            parent=parent_win,
        )
