"""Export a SessionContext as a Jupyter notebook and open it in VS Code.

The "Export to Notebook..." bridge: reproduces the pipeline run in the GUI
so far as a fresh, runnable notebook, so the user can keep going with full
notebook flexibility (re-run with different parameters, compare runs side
by side, etc.) -- see the molass-gui design philosophy note in repo memory
(2026-08-20). Note this is a re-run from scratch, not a live handoff of the
GUI's in-memory state -- "Export", not "Continue", to avoid implying the
notebook resumes execution rather than restarting it.
"""
import os
import shutil
import subprocess
from tkinter import filedialog, messagebox

import nbformat as nbf


def _md(source):
    return nbf.v4.new_markdown_cell(source)


def _code(source):
    return nbf.v4.new_code_cell(source)


def _upgrade_call(model_info):
    model_key = model_info['model']
    pore_dist = model_info.get('pore_dist')
    ln_pore_sigma = model_info.get('ln_pore_sigma')
    kwargs = ""
    if pore_dist is not None:
        kwargs += f", pore_dist={pore_dist!r}"
    if ln_pore_sigma is not None:
        kwargs += f", model_params={{'ln_pore_sigma': {ln_pore_sigma!r}}}"
    return f"decomp = decomp.upgrade({model_key!r}{kwargs})"


def build_notebook(ctx):
    """Build an nbformat notebook reproducing ctx's pipeline so far."""
    cells = [_md(
        "# Molass session -- exported from GUI\n\n"
        "Generated by molass-gui's \"Export to Notebook...\" -- re-runs the same "
        "pipeline from scratch with full notebook flexibility (re-run with "
        "different parameters, compare runs side by side, etc.)."
    )]

    cells.append(_code(
        "from molass.DataObjects import SecSaxsData as SSD\n\n"
        f"ssd = SSD(r\"{ctx.folder}\")\n"
        "trimmed = ssd.trimmed_copy()\n"
        "trimmed.plot_compact(baseline=True)"
    ) if ctx.dropbox_path is None else _code(
        # Resolve via Dropbox on every run (cheap no-op when unchanged) rather
        # than baking in the raw local path -- reading that directly would
        # defeat the whole point of sync_dropbox_folder (repeated re-downloads
        # from an "online-only" Dropbox-synced folder). Also more portable: a
        # Dropbox-relative path works on any machine with valid credentials,
        # unlike a machine-specific local mount path.
        "from molass.DataObjects import SecSaxsData as SSD\n"
        "from molass.DataUtils import sync_dropbox_folder\n\n"
        f"data_folder = sync_dropbox_folder(r\"{ctx.dropbox_path}\")\n"
        "ssd = SSD(data_folder)\n"
        "trimmed = ssd.trimmed_copy()\n"
        "trimmed.plot_compact(baseline=True)"
    ))

    if ctx.num_components is not None:
        proportions = getattr(ctx, 'proportions', None)
        proportions_kwarg = f", proportions={proportions}" if proportions else ""
        ranks_line = (f"decomp.update_xr_ranks({ctx.xr_ranks})\n"
                     if getattr(ctx, 'xr_ranks', None) is not None else "")
        cells.append(_code(
            "corrected = trimmed.corrected_copy()\n"
            f"decomp = corrected.quick_decomposition(num_components={ctx.num_components}"
            f"{proportions_kwarg})\n"
            f"{ranks_line}"
            "rgcurve = decomp.get_rg_curve()\n"
            "decomp.plot_components(rgcurve=rgcurve)"
        ))

    if ctx.model_info is not None and ctx.model_info['model'] != 'egh':
        cells.append(_code(_upgrade_call(ctx.model_info) + "\ndecomp.plot_components(rgcurve=rgcurve)"))

    if ctx.method is not None:
        cells.append(_code(
            "score = decomp.score(trimmed_ssd=trimmed)\n"
            "score.print_summary()\n"
            "score.plot()"
        ))
        # in_process, async_, monitor, and pipeline_recipe are all deliberately
        # omitted -- they already match the library's own defaults (False, True,
        # True, None), and this is the usual pattern anyway. Both the GUI and the
        # exported notebook now get the same subprocess+auto-recipe behavior "for
        # free" from the library default -- see
        # molass-library/Copilot/refactor/DESIGN_default_in_process_reversal.md.
        # method is always shown, even for 'BH': it incurs zero learning cost
        # (the user already saw/chose BH in the GUI's own combobox), so restating
        # it just makes an already-known fact explicit and reproducible. This
        # differs from in_process/async_/monitor above, which were never GUI-facing
        # choices -- surfacing them would require learning a new concept for no
        # benefit, which is what the "minimal learning cost" rule guards against.
        lines = [
            "# Sibling folder, not the GUI's own analysis_folder -- reusing that path",
            "# exactly can collide with the GUI's own run still using it (optimize_rigorously",
            "# would just reconnect to it instead of starting a fresh monitored run).",
            f'analysis_folder = r"{ctx.analysis_folder}_notebook"',
        ]
        num_jobs = getattr(ctx, 'num_jobs', None)
        # Honestly re-express the GUI's auto_constraint=False decision as an
        # explicit constraints=[] here -- pipeline_recipe itself is deliberately
        # never shown (see the comment block above), so this is the only way
        # the exported script wouldn't silently pick up the library's own
        # default auto-applied LumpingConstraint, which the equal-split
        # fallback proportions (not a user choice) shouldn't seed.
        constraints_kwarg = ([] if not getattr(ctx, 'trust_proportions', True) else None)
        if num_jobs and num_jobs > 1:
            # Successive-jobs pattern (molass-researcher experiment 36): each
            # round reseeds init_params from the best params found so far.
            # num_jobs requires async_=False -- the call blocks until every
            # round completes (see optimize_rigorously docs).
            lines += [
                "run_info = decomp.optimize_rigorously(",
                "    trimmed_ssd=trimmed,",
                f"    method={ctx.method.upper()!r},",
                "    analysis_folder=analysis_folder,",
                f"    num_jobs={num_jobs},",
                "    async_=False,",
            ]
            if constraints_kwarg is not None:
                lines.append("    constraints=[],  # equal-split fallback proportions -- not user-vouched-for")
            lines.append(")")
        else:
            lines += [
                "run_info = decomp.optimize_rigorously(",
                "    trimmed_ssd=trimmed,",
                f"    method={ctx.method.upper()!r},",
                "    analysis_folder=analysis_folder,",
            ]
            if constraints_kwarg is not None:
                lines.append("    constraints=[],  # equal-split fallback proportions -- not user-vouched-for")
            lines.append(")")
        cells.append(_code("\n".join(lines)))
        cells.append(_code("run_info.live_status()"))

    nb = nbf.v4.new_notebook()
    nb['cells'] = cells
    return nb


def _open_in_vscode(path):
    for exe in ("code-insiders", "code"):
        found = shutil.which(exe)
        if found:
            subprocess.Popen([found, path])
            return True
    return False


def build_restore_notebook(analysis_folder):
    """Build an nbformat notebook that reconnects to an existing analysis_folder.

    Unlike build_notebook() (which re-runs the whole GUI pipeline from
    scratch), this is the "Open Existing Analysis" / result_mode counterpart:
    it reconnects to a run that may already be finished. The notebook checks
    the run's live phase and branches: if the GUI (or anything else) still has
    an optimization running against this analysis_folder, this starts a fresh
    optimization of its own into a sibling "_notebook" folder -- same
    collision-avoidance pattern as build_notebook() -- instead of reusing the
    GUI's own path, which optimize_rigorously() would just silently reconnect
    to; if it's idle, this just shows the current best score, at no cost.
    """
    cells = [_md(
        "# Molass session -- restored from GUI\n\n"
        "Generated by molass-gui's \"Export to Notebook...\" from an existing "
        "analysis. If the optimization is still running (in the GUI or "
        "elsewhere), this runs its own optimization into a sibling folder; "
        "if it's idle, this just shows the current best score."
    )]

    cells.append(_code(
        "from molass.Rigorous.RecipeRunner import rebuild_decomposition_from_recipe\n"
        "from molass.Rigorous.RunInfo import RunInfo\n\n"
        f"analysis_folder = r\"{analysis_folder}\"\n"
        "ssd, trimmed, decomp, recipe = rebuild_decomposition_from_recipe(analysis_folder)"
    ))

    cells.append(_code(
        "run_info = RunInfo.reconnect(analysis_folder, raise_if_not_found=False)\n"
        "phase = run_info.live_status()['phase'] if run_info is not None else 'completed'\n"
        "print(f\"phase: {phase}\")\n"
        "\n"
        "if phase == 'running':\n"
        "    # Sibling folder, not the GUI's own analysis_folder -- reusing that path\n"
        "    # exactly would make optimize_rigorously() silently reconnect to (and thus\n"
        "    # share job history with) the GUI's still-running optimizer.\n"
        "    notebook_analysis_folder = analysis_folder + \"_notebook\"\n"
        "    run_info = decomp.optimize_rigorously(\n"
        "        trimmed_ssd=trimmed,\n"
        "        method=recipe.get('method', 'bh').upper(),\n"
        "        analysis_folder=notebook_analysis_folder,\n"
        "    )\n"
        "    run_info.live_status()\n"
        "else:\n"
        "    score_before = decomp.score(trimmed_ssd=trimmed, function_code=recipe.get('function_code'))\n"
        "    run_info.optimizer = score_before.optimizer  # reconnect() has no live optimizer\n"
        "    score = run_info.score()\n"
        "    score.print_summary()\n"
        "    score.plot()"
    ))

    nb = nbf.v4.new_notebook()
    nb['cells'] = cells
    return nb


def _ask_path_write_and_open(nb, default_name, parent_win):
    """Ask for a save path, write nb, open it in VS Code.

    Shared tail end of export_and_open()/export_restore_and_open(). Failures
    are shown as a messagebox rather than raised -- this is a convenience
    bridge, not a critical path; the GUI session keeps working regardless of
    the outcome.
    """
    path = filedialog.asksaveasfilename(
        title="Save notebook as",
        defaultextension=".ipynb",
        filetypes=[("Jupyter Notebook", "*.ipynb")],
        initialfile=default_name,
        parent=parent_win,
    )
    if not path:
        return

    overwriting_existing = os.path.exists(path)

    try:
        nbf.write(nb, path)
    except Exception as exc:
        messagebox.showerror("Export failed", str(exc), parent=parent_win)
        return

    if not _open_in_vscode(path):
        messagebox.showinfo(
            "Notebook saved",
            f"Saved to:\n{path}\n\n(VS Code CLI not found on PATH -- open it manually.)",
            parent=parent_win,
        )
    elif overwriting_existing:
        messagebox.showinfo(
            "Notebook updated",
            "If this notebook was already open in VS Code, its tab may not "
            "auto-refresh -- close and reopen the tab to see the update.",
            parent=parent_win,
        )


def export_and_open(ctx, parent_win):
    """Ask for a save path, write the notebook, open it in VS Code."""
    from datetime import datetime
    # Timestamped default name -- a reused fixed name (e.g. molass_session.ipynb)
    # would silently reopen an already-open stale tab: VS Code's notebook editor
    # does not reliably auto-reload an open .ipynb when it changes on disk
    # externally, so re-exporting to the same path can appear to "not work"
    # even though the file itself was written correctly (see repo memory).
    default_name = f"molass_session_{datetime.now():%Y%m%d_%H%M%S}.ipynb"
    try:
        nb = build_notebook(ctx)
    except Exception as exc:
        messagebox.showerror("Export failed", str(exc), parent=parent_win)
        return
    _ask_path_write_and_open(nb, default_name, parent_win)


def export_restore_and_open(analysis_folder, parent_win):
    """Ask for a save path, write the restore notebook, open it in VS Code."""
    from datetime import datetime
    default_name = f"molass_restore_{datetime.now():%Y%m%d_%H%M%S}.ipynb"
    try:
        nb = build_restore_notebook(analysis_folder)
    except Exception as exc:
        messagebox.showerror("Export failed", str(exc), parent=parent_win)
        return
    _ask_path_write_and_open(nb, default_name, parent_win)
